In [9]:
import pandas as pd
import numpy as np

In [10]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print('Сложение:', a+b)
print('Вычитание:', a-b)

Сложение: [15 23 14  8]
Вычитание: [ 5 -7 -4 -6]


### Практика. Векторы (юнит 3)

In [11]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

display(Hut_Paradise_DF)

#Задание 3.5
print(Hut_Paradise_DF['2.Area'].values-Hut_Paradise_DF['6.Liv.Area'].values)

#Задание 3.6
Hut_Paradise_DF['7.Demo.dura'] = [10, 20, 30, 15, 5, 40, 20, 8, 20] 
print('Скалярное произведение:', np.dot(Hut_Paradise_DF['7.Demo.dura'], Hut_Paradise_DF['5.Demo two weeks']))

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

[13 12 15 13 17  9 20 15 25]
Скалярное произведение: 1348


In [12]:
#Задание 3.7
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('Линейная комбинация:', 0*u+2*v+(-3*w))
np.dot(u, 0*u+2*v+(-3*w))

Линейная комбинация: [-3 14  3  4  2]


0

### Практика. Матрицы (юнит 5)

In [13]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

#Задание 5.1
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
print(Inc)

print('-'*50)

#Задание 5.2
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
print(Cons)

print('-'*50)

#Задание 5.3
clear_inc = Inc - Inc*0.13
print(clear_inc)

print('-'*50)

#Задание 5.4
balance = clear_inc - Cons
print(balance)

[[100 150  90]
 [220 200  80]
 [140 130 100]]
--------------------------------------------------
[[ 50 100 100]
 [ 50  80  20]
 [ 60 140 140]]
--------------------------------------------------
[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]
--------------------------------------------------
[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


In [14]:
A = np.array([[1, -5], [2, 2], [0, 3]])
B = np.array([[3, 1, 0], [-1, 0, 2]])

print(A@B)
print(B@A)

[[  8   1 -10]
 [  4   2   4]
 [ -3   0   6]]
[[  5 -13]
 [ -1  11]]


### Практика. Матричное умножение.

In [15]:
# Задание 7.1
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

print(A@x)
print('-'*50)
#Задание 7.2
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

print(A,'\n', B)
print(B@A)
print('-'*50)

#Задание 7.3
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x,y,z])
print('')

#Задание 7.4
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
comission = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

display(Count_DF)
display(Price_DF)

commissions_array = (Price_DF.values*Count_DF.values)@comission
print('Получено с каждого коммисионных:', commissions_array)
print('-'*50)

#Задание 7.5
print('Доходы каждого стилиста:', (Price_DF.values*Count_DF.values)@(np.ones(5)-comission))

[26 30]
--------------------------------------------------
[[1 9 8 5]
 [3 6 3 2]
 [3 3 3 3]
 [0 2 5 9]
 [4 4 1 2]] 
 [[ 1 -1  0  1  1]
 [-2  0  2 -1  1]]
[[  2   9  11  14]
 [  8 -10 -14 -11]]
--------------------------------------------------



Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

Получено с каждого коммисионных: [11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]
--------------------------------------------------
Доходы каждого стилиста: [ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [16]:
# Задания 8.2, 8.3 и 8.4
A = [[1,2], [2,5]]
Ainv = np.linalg.inv(np.array(A))
print(np.array(A)@Ainv)

# Задание 8.6
A = [[1,2], [1,1]]
B = [[5,-2], [-1,4]]


[[1. 0.]
 [0. 1.]]


#### Практика. Обратная матрица, определитель, ранг.

In [32]:
# Задание 10.1
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
print(np.linalg.inv(A))
print('-'*50)

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

# Задание 10.2
matrix_system = np.array([v1, v2, v3, v4]).T
print('Ранг совокупной матрицы:', np.linalg.matrix_rank(matrix_system))
print('-'*50)

#Задание 10.3
print(matrix_system)
print('-'*50)

#Задание 10.4
G = matrix_system.T@matrix_system
print('Матрица Грамма:', G)
print('-'*50)

#Задание 10.5
print('Определитель матрицы Грамма:', round(np.linalg.det(G)))
print('-'*50)

#Задание 10.7
print('Обратная матрица матрице Грамма:\n',
      np.round(np.linalg.inv(G), 3))

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]
--------------------------------------------------
Ранг совокупной матрицы: 4
--------------------------------------------------
[[ 9  2  4  3]
 [10  0  0 -4]
 [ 7  5  0  3]
 [ 7  1  4 -1]
 [ 9  4  1 -4]]
--------------------------------------------------
Матрица Грамма: [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]
--------------------------------------------------
Определитель матрицы Грамма: 3716648
--------------------------------------------------
Обратная матрица матрице Грамма:
 [[ 0.017 -0.028 -0.026  0.016]
 [-0.028  0.072  0.03  -0.027]
 [-0.026  0.03   0.077 -0.026]
 [ 0.016 -0.027 -0.026  0.035]]
