In [65]:
import numpy as np
import pandas as pd

In [66]:
df = pd.read_csv('data/Advertising.csv', index_col=0)
display(df.head())
display(df.info())

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


None

In [67]:
X = df['TV']
y = df['sales']
n = len(y)
X = np.append(np.ones((n,1)), X.values.reshape(n,1), axis = 1)
y = df['sales'].values.reshape(n,1)
par = np.zeros((2,1))

In [68]:
def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

In [69]:
def grad_d(X, y, par, alpha, iterations, eps=0.001):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))
        par -= alpha * 1 / n * der
        costs.append(cost_function(X, y, par))
        # Добавили критерий остановки в алгоритм - длина вектора градиента меньше либо равна eps
        # Это случается, когда все компоненты вектора градиента близки к eps (почти 0)
        if np.linalg.norm(der) <= eps:
            # В случае выполнения критерия остановки алгоритм завершает работу
            break
    return par, costs

In [70]:
par_opt, costs_opt = grad_d(X, y, par, 0.00005, 500000)
print(par_opt)

[[7.02008789]
 [0.04760015]]


In [71]:
# Задание 8.3
display(df.head())
X = df[['TV', 'radio', 'newspaper']]
y = df['sales']
n = len(y)
X = np.append(np.ones((n, 1)), X.values.reshape(n, 3), axis = 1)
y = df['sales'].values.reshape(n, 1)
par = np.zeros((4, 1))
#Для проверки
display(X[:3])
display(par)

#Функция OLS
def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

#Функция градиентного спуска
def grad_d(X, y, par, alpha, iterations, eps=0.001):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))
        par -= alpha * 1 / n * der
        costs.append(cost_function(X, y, par))
        # Добавили критерий остановки в алгоритм - длина вектора градиента меньше либо равна eps
        # Это случается, когда все компоненты вектора градиента близки к eps (почти 0)
        if np.linalg.norm(der) <= eps:
            # В случае выполнения критерия остановки алгоритм завершает работу
            break
    return par, costs

par_opt, costs_opt = grad_d(X, y, par, 0.00005, 500000)
print(par_opt.round(3))

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3]])

array([[0.],
       [0.],
       [0.],
       [0.]])

[[ 2.863e+00]
 [ 4.600e-02]
 [ 1.890e-01]
 [-1.000e-03]]


In [ ]:
#Эталон

import pandas as pd
import numpy as np

df = pd.read_csv('data/Advertising.csv', index_col=0)

X = df[['TV','radio','newspaper']]
y = df['sales']
n = len(y)
X = np.append(np.ones((n,1)), X.values.reshape(n,3), axis = 1)
y = df['sales'].values.reshape(n,1)
par = np.zeros((4,1))

def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

def grad_d(X,y, par, alpha, iterations, eps=0.001):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))/ n
        par -= alpha * der
        costs.append(cost_function(X,y, par))
        if np.linalg.norm(der) < eps:
            break
    return par, costs

par, costs = grad_d(X,y, par, 0.00005, 500000)
print(par.round(3))

[[ 2.863e+00]
 [ 4.600e-02]
 [ 1.890e-01]
 [-1.000e-03]]


In [73]:
import numpy as np
import statsmodels.api as sm
mod = sm.OLS(y, X)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Tue, 24 Jun 2025   Prob (F-statistic):           1.58e-96
Time:                        21:54:17   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

In [74]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
print(model.coef_)
print(model.intercept_)

[[ 0.          0.04576465  0.18853002 -0.00103749]]
[2.93888937]
